version: "3.9"  # Указывает версию синтаксиса docker-compose

services:  # Определяет сервисы, которые будут запущены
  base:  # Имя сервиса - База данных
    container_name: audio_container  # Имя контейнера
    image: postgres:14.0-alpine  # Используемый образ
    restart: always  # Политика перезапуска (всегда перезапускать)
    environment:  # Переменные окружения для контейнера
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:  # Сопоставление путей каталогов между хостом и контейнером
      - ./data/db:/var/lib/postgresql/data_audio  # Сохранение данных базы данных на хосте
    ports:  # Открытие портов
      - "5432:5432"  # Сопоставление портов между хостом и контейнером
  pgadmin:  # Сервис - веб-интерфейс для управления базой данных
    container_name: audio_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:  # Сопоставление портов
      - "5050:80"

  web:  # Сервис - наше веб-приложение
    build: .  # Путь к Dockerfile, который будет использоваться для сборки образа (в той же директории, что и docker-compose.yml)
    command: uvicorn main:app --host 0.0.0.0 --port 8000  # Команда, запускаемая в контейнере
    volumes:
      - .:/app  # Сопоставление каталогов
    ports:
      - "8000:8000"  # Сопоставление портов
    depends_on:  # Указывает на зависимость от другого сервиса
      - base  # Веб-приложение зависит от базы данных